chat/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.startpage, name="start-page"),
    path('signup/', views.signup, name="signup"),
    path('login/', LoginView.as_view(template_name='chat/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat')),
    path('rooms/', include('room.urls', namespace='room')),
]

room/urls.py
from django.urls import path
from . import views

app_name = 'room'

urlpatterns = [
    path('', views.rooms, name="rooms"),
    path('<slug:slug>/', views.room, name="room"),
]

chat/models.py
from django.db import models

# Create your models here.

room/models.py
from django.db import models


class Room(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

chat/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SigupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

chat/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import login
from .forms import SigupForm


def startpage(request):
    return render(request, 'chat/startpage.html')



def signup(request):
    form = SigupForm()
    if request.method == 'POST':
        form = SigupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return reverse('chat:start-page')
    return render(request, 'chat/signup.html', {'form': form})

room/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Room


@login_required
def rooms(request):
    rooms = Room.objects.all()

    return render(request, 'room/rooms.html', {'rooms': rooms})

@login_required
def room(request, slug):
    room = Room.objects.get(slug=slug)

    return render(request, 'room/room.html', {'room': room})

chat/templates/chat/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %}{% endblock title %} Web Chat</title>
    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        .chat-messages{
            height: 400px;
            overflow-y: auto;
        }
    </style>
</head>
<body class="bg-teal-600">
    <nav class="flex items-center justify-between px-4 py-6 bg-teal-800">
        <div>
            <a href="/" class="text-xl text-white">Web Chat</a>
        </div>
        <div class="flex items-center space-x-4">
            
            {% if request.user.is_authenticated %}
                <a href="{% url 'room:rooms' %}" class="text-white hover:text-gray-200">Rooms</a> 

                <a href="{% url 'chat:logout' %}" class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700">Logout</a>
            {% else %}
                <a href="/login/" class="text-white hover:text-gray-200">Login</a>

                <a href="{% url 'chat:signup' %}" class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700">Signup</a>
            {% endif %}
                
        </div>
    </nav>

    
    {% block content %}
        
    {% endblock content %}

    
    {% block scripts %}
        
    {% endblock scripts %}
        
        
</body>
</html>

chat/templates/chat/login.html
{% extends 'chat/base.html' %}


{% block title %}
    Login |
{% endblock title %}
    

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <div class="text-3xl lg:text-6xl text-white">Log in</div>
</div>

<form method="post" action="." class="lg:w-1/4 px-4 mx-auto">
    {% csrf_token %}

    <div class="mb-5">
        <label class="text-white">Username</label>
        <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Password</label>
        <input type="password" name="password" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                    <p>{{ error|escape }}</p>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <button type="submit" class="px-5 py-3 rounded-xl text-white bg-teal-800 hover:bg-teal-700">Login</button>

</form>
{% endblock content %}
    

chat/templates/chat/signup.html
{% extends 'chat/base.html' %}


{% block title %}
    Signup |
{% endblock title %}
    

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <div class="text-3xl lg:text-6xl text-white">Sign up</div>
</div>

<form method="post" action="." class="lg:w-1/4 px-4 mx-auto">
    {% csrf_token %}

    <div class="mb-5">
        <label class="text-white">Username</label>
        <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Password</label>
        <input type="password" name="password1" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>
    
    <div class="mb-5">
        <label class="text-white">Confirm password</label>
        <input type="password" name="password2" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                    <p>{{ error|escape }}</p>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <button type="submit" class="px-5 py-3 rounded-xl text-white bg-teal-800 hover:bg-teal-700">Submit</button>

</form>
{% endblock content %}
    

chat/templates/chat/startpage.html
{% extends 'chat/base.html' %}


{% block title %}
    Welcome |
{% endblock title %}
    

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <div class="text-3xl lg:text-6xl text-white">Web Chat</div>
</div>
{% endblock content %}
    

room/templates/room/room.html
{% extends 'chat/base.html' %}


{% block title %}
    {{ room.name }} |
{% endblock title %}
    

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <div class="text-3xl lg:text-6xl text-white">{{ room.name }}</div>
</div>

<div class="lg:w-2/4 mx-4 lg:mx-auto  p-4 bg-white rounded-xl">
    <div class="chat-messages space-y-3" id="chat-messages">
        <div class="p-4 bg-gray-200 rounded-xl">
            <p class="font-semibold">Username</p>
            <p>The test message xyz abc.</p>
        </div>

        <div class="p-4 bg-gray-200 rounded-xl">
            <p class="font-semibold">Username</p>
            <p>The test message xyz abc.</p>
        </div>

        <div class="p-4 bg-gray-200 rounded-xl">
            <p class="font-semibold">Username</p>
            <p>The test message xyz abc.</p>
        </div>
    </div>
</div>

<div class="lg:w-2/4 mt-6 mx-4 lg:mx-auto  p-4 bg-white rounded-xl">
    <form action="." method="post" class="flex">
        <input type="text" name="content" class="flex-1 mr-3" placeholder="Your message..." id="chat-message-input"/>
        <button class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700"
            id="chat-message-submit">
        Submit
    </button>
    </form>
</div>
{% endblock content %}

{% block scripts %}
    {{ room.slug|json_script:"json-roomname" }}
    {{ request.user.username|json_script:"json-username" }}
    <script>
        const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
        const userName = JSON.parse(document.getElementById('json-username').textContent);

        const chatSocket = new WebSocket(
            `ws://${window.location.host}/ws/${roomName}/`
        )

        chatSocket.onmessage = function(e){
            console.log('onmessage');
            const data = JSON.parse(e.data);

            if(data.message){
                let html = '<div class="p-4 bg-gray-200 rounded-xl">';
                    html += '<p class="font-semibold">' + data.username + '</p>';
                    html += '<p>' + data.message + '</p></div>';
                
                document.querySelector('#chat-messages').innerHTML += html;
                scrollToBottom();

            }else{
                alert('The message was empty');
            }
        }

        chatSocket.onclose = function(e){
            console.log('onclose');
        }

        document.querySelector('#chat-message-submit').onclick = function(e){
            e.preventDefault();

            const messageInput = document.querySelector('#chat-message-input');
            const message = messageInput.value;

            chatSocket.send(JSON.stringify({
                'message': message,
                'username': userName,
                'room': roomName
            }));

            messageInput.value = '';

            return false;
        }

        function scrollToBottom(){
            const objDiv = document.querySelector('#chat-messages');
            objDiv.scrollTop = objDiv.scrollHeight;
        }

        scrollToBottom();
    </script>    
{% endblock scripts %}
    

room/templates/room/rooms.html
{% extends 'chat/base.html' %}


{% block title %}
    Rooms |
{% endblock title %}
    

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <div class="text-3xl lg:text-6xl text-white">Rooms</div>
</div>

<div class="w-full flex flex-wrap items-center">
    
    {% for room in rooms %}
        <div class="w-full lg:w-1/4 px-3 py-3">
            <div class="p-4 bg-white shadow rounded-xl text-center">
                <h2 class="mb-5 text-2xl font-semibold">{{ room.name }}</h2>

                <a href="{% url 'room:room' room.slug %}" class="px-5 py-3 block rounded-xl text-white bg-teal-600 hover:bg-teal-700">
                    Join
                </a>
            </div>
        </div>
    {% endfor %}
        
</div>
{% endblock content %}
    